[program:moodle-cron]
command=/usr/local/bin/moodle-cron
user=www-data
priority=50
autostart=true
autorestart=true
startsecs=0
stopsignal=TERM
stopwaitsecs=60
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
