[program:redis]
command=/usr/bin/redis-server /etc/redis/moodle.conf
user=redis
priority=20
autostart=true
autorestart=true
stopsignal=TERM
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
